In [1]:
import numpy as np
import pandas as pd
import cv2
import random
from sklearn.metrics import confusion_matrix
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import metrics
from mostCommon import most_common
from sklearn.metrics import f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import math

In [2]:
my_data = pd.read_csv('../data/Five_Frames_Per_patient.csv')
patients_data=pd.read_csv('../data/videos_data.csv')
data_array = my_data.to_numpy()
patients_array=patients_data["FileName"].to_numpy()
images_path = '../data/Five_Frames_Per_patient/'
no_of_test_patients=math.floor(patients_array.size*0.2) 
images_data = []
models = []

In [3]:
rand_indexes=[]
test_patients=[]
while len(rand_indexes)<no_of_test_patients:
    h=random.randint(0, 121)
    if h not in rand_indexes:
        rand_indexes.append(h)
rand_indexes = sorted(rand_indexes, reverse=True) 
for i in range(len(rand_indexes)):
    test_patients.append(np.take(patients_array,rand_indexes[i]))
    patients_array= np.delete(patients_array, rand_indexes[i])

In [4]:
#I got my patients names now i need to get their frames from my_data

df=my_data
test_data=[]
for i in range(len(test_patients)):
    contain_values = df[df['FileName'].str.contains(test_patients[i])].to_numpy()
    if len(contain_values) == 0:
        print(test_patients[i]+'        Duplicate')
    test_data.append(contain_values)
    indexes = df[df['FileName'].str.contains(test_patients[i])].index
    df.drop(indexes, inplace = True )

Cov-Atlas-Day+4        Duplicate
Cov-Atlas-Day+1        Duplicate
Cov-Atlas+(45)        Duplicate


C:\Users\RS3\AppData\Roaming\Python\Python39\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)


In [5]:
X_train=[]
X_test=[]
y_train=[]
y_test=[]

In [8]:
data_array=df.to_numpy()
for i in data_array:
    img = cv2.imread(images_path + i[0] + '.' + i[2], cv2.IMREAD_GRAYSCALE)
    img = cv2.equalizeHist(img)
    print(img)
    img = cv2.resize(img, (224, 224), interpolation=cv2.INTER_AREA)
    img_1d = img.reshape(224 * 224)
    images_data.append(img_1d)
X_train=np.asarray(images_data)
y = np.asarray(my_data['Label'])

[[  6   0  10 ... 154 116 105]
 [ 10   0   0 ... 160 134 131]
 [  0   6  10 ... 141 131 138]
 ...
 [ 23  15  28 ...   0   0   0]
 [ 30  21  30 ...   0   0   0]
 [ 26  23  28 ...   0   0   0]]
[[  6   0   6 ... 149 142 149]
 [  0   0   0 ... 156 145 158]
 [  0  10   0 ... 165 149 152]
 ...
 [ 18  29  34 ...   0   6   6]
 [ 21  31  37 ...   0  16  31]
 [ 27  27  23 ...   0   0   0]]
[[  7   0   0 ... 176 161 146]
 [  0   7   0 ... 146 153 158]
 [  7   0  10 ... 165 158 149]
 ...
 [ 35  22  30 ...   0   0   0]
 [ 32  25  30 ...   7   0   0]
 [ 22  25  25 ...   7   7   0]]
[[ 14   0   0 ... 170 175 192]
 [  0  11  11 ... 163 159 178]
 [  0  11   0 ... 151 144 163]
 ...
 [ 33  41  50 ...   0   0   0]
 [ 28  28  30 ...   0   0   0]
 [ 30  20  20 ...   0   0   0]]
[[  0  10   0 ... 163 160 154]
 [  6   6   0 ... 132 112 129]
 [  0   0   0 ... 160 144 191]
 ...
 [ 10  16  14 ...   0   0   0]
 [ 27  25  14 ...   0   0   0]
 [ 16  23  23 ...   0   0   0]]
[[ 0  0 16 ...  0  0  0]
 [16  0 16 ... 

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [ 40  34  35 ... 189 189 189]
 [ 32  26  26 ... 181 180 178]
 [ 26  23  21 ... 170 169 167]]
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [12 12 12 ... 18 19 19]
 [15 14 13 ... 15 16 17]
 [17 15 14 ... 15 16 16]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [ 20  19  18 ...  73  71  78]
 [ 17  17  17 ...  91  83  91]
 [ 16  16  16 ... 109  94 103]]
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [20 20 19 ... 48 36 32]
 [16 18 19 ... 60 48 43]
 [15 17 18 ... 70 58 52]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [4 4 4 ... 4 4 3]
 [0 0 1 ... 3 2 1]
 [1 0 0 ... 2 1 0]]
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 4  6 10 ...  3  3  3]
 [ 1  2  2 ...  2  0  0]
 [ 0  0  0 ...  0  0  0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 .

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[55 55 55 ... 55 55 55]
 [55 55 55 ... 55 55 55]
 [55 55 55 ... 55 55 55]
 ...
 [55 55 55 ... 55 55 55]
 [55 55 55 ... 55 55 55]
 [55 55 55 ... 55 55 55]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[62 62 62 ... 62 62 62]
 [62 62 62 ... 62 62 62]
 [62 62 62 ... 62 62 62]
 ...
 [62 62 62 ... 62 62 62]
 [62 62 62 ... 62 62 62]
 [62 62 62 ... 62 62 62]]
[[62 62 62 ... 62 62 62]
 [62 62 62 ... 62 62 62]
 [62 62 62 ... 62 62 62]
 ...
 [62 62 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [61 61 61 ... 47 47 47]
 [67 67 67 ... 47 47 47]
 [68 68 68 ... 47 47 47]]
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [53 53 53 ... 53 53 53]
 [53 53 53 ... 53 53 53]
 [53 53 53 ... 53 53 53]]
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [76 72 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

In [7]:
patients_images=[]
for patient in test_data:
    for i in patient:
        img = cv2.imread(images_path + i[0] + '.' + i[2], cv2.IMREAD_GRAYSCALE)
        img = cv2.equalizeHist(img)
        img = cv2.resize(img, (224, 224), interpolation=cv2.INTER_AREA)
        img_1d = img.reshape(224 * 224)
        X_test.append(img_1d)
        y_test.append(i[1])

In [20]:
# Now I have xtrain xtest ytrain ytest ready I should increment them in X
print(len(X_train))
print(len(y))
print(len(X_test))
print(len(y_test))

470
470
140
140


In [22]:
r = []
conf_matricies = []
f1_reports = []
f1_micro = []
pc=[0,0]
totpc=[]
t=100
while t<276:
    r=[]
    for i in range(1):
        r.append(random.randint(0, 1000))
    print('Random seeds are: '+str(r))

    number_of_models = 11
    X = np.asarray(images_data)
    y = np.asarray(my_data['Label'])

    for k in range(len(r)):
        print('--------------------------------- Iteration ' + str(k) + '--------------------------------- \n')
        Xandy = []
        models = []
        # creating models
        for i in range(number_of_models):
            models.append(make_pipeline(StandardScaler(), SVC(gamma='auto', random_state=r[k])))

        # Creating array test splits for models
        # X_train, X_test, y_train, y_test
        for i in range(number_of_models):
            #append x train x test y train ytest to x
            x=[]
            x.append(X_train)
            x.append(X_test)
            x.append(y)
            x.append(y_test)
            Xandy.append(x)

        print('Equalizing Data...')
        for i in range(number_of_models):
            x = Xandy[i][0]
            y1 = Xandy[i][2]
            cov = np.count_nonzero(y1 == 'covid')
            pneu = np.count_nonzero(y1 == 'pneumonia')
            reg = np.count_nonzero(y1 == 'regular')+10
            # deleting random pneumonia elements from each model set
            while cov != pneu:
                index = random.randint(0, len(x) - 1)
                if y1[index] == 'pneumonia':
                    x = np.delete(x, index, 0)
                    y1 = np.delete(y1, index, 0)
                    pneu -= 1
            # deleting random regular elements from each model set
            while cov != reg:
                index = random.randint(0, len(x) - 1)
                if y1[index] == 'regular':
                    x = np.delete(x, index, 0)
                    y1 = np.delete(y1, index, 0)
                    reg -= 1
            Xandy[i][0] = x
            Xandy[i][2] = y1

        print('Normalizing and applying PCA...')
        for i in range(number_of_models):
            scaler = StandardScaler()
            # Fit on training set only
            scaler.fit(Xandy[i][0])

            # Apply transform on both training and test set
            Xandy[i][0] = scaler.transform(Xandy[i][0])
            Xandy[i][1] = scaler.transform(Xandy[i][1])
        for i in range(number_of_models):
            pca = PCA(n_components=t)
            pca.fit(Xandy[i][0])
            Xandy[i][0] = pca.transform(Xandy[i][0])
            Xandy[i][1] = pca.transform(Xandy[i][1])
        print(len(Xandy[0][0][0]))
        print('Training Models...')
        for i in range(number_of_models):
            models[i].fit(Xandy[i][0], Xandy[i][2])

        print('getting predictions of each model...')
        predicted = []
        for i in range(number_of_models):
            predicted.append(models[i].predict(Xandy[i][1]))

        voted_prediction = []
        for i in range(len(predicted[0])):
            voting = []
            for j in range(len(predicted)):
                voting.append(predicted[j][i])
            voted_prediction.append(most_common(voting))
        conf_matrix = confusion_matrix(Xandy[0][3], voted_prediction)
        #print(conf_matrix)
        conf_matricies.append(conf_matrix)

        classification_report = metrics.classification_report(Xandy[0][3], voted_prediction, digits=3)
        #print(classification_report)
        f1_reports.append(classification_report)
        f1_micro.append(f1_score(Xandy[0][3], voted_prediction, average='micro'))
    print('Pca is: '+str(t))
    pc[0]=t
    pc[1]=str(sum(f1_micro) / len(f1_micro))
    totpc.append(pc)
    print('Average f1 micro of all iterations is: ' + str(sum(f1_micro) / len(f1_micro)))
    t+=1
   # print('Saving models....')
    #np.save('models', models)
    print('All Done :)')

Random seeds are: [331]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
100
Training Models...
getting predictions of each model...
Pca is: 100
Average f1 micro of all iterations is: 0.6857142857142857
All Done :)
Random seeds are: [850]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
101
Training Models...
getting predictions of each model...
Pca is: 101
Average f1 micro of all iterations is: 0.7
All Done :)
Random seeds are: [425]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
102
Training Models...
getting predictions of each model...
Pca is: 102
Average f1 micro of all iterations is: 0.7047619047619048
All Done :)
Random seeds are: [809]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data.

--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
128
Training Models...
getting predictions of each model...
Pca is: 128
Average f1 micro of all iterations is: 0.7189655172413792
All Done :)
Random seeds are: [380]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
129
Training Models...
getting predictions of each model...
Pca is: 129
Average f1 micro of all iterations is: 0.7192857142857142
All Done :)
Random seeds are: [127]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
130
Training Models...
getting predictions of each model...
Pca is: 130
Average f1 micro of all iterations is: 0.7221198156682027
All Done :)
Random seeds are: [381]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normal

Pca is: 155
Average f1 micro of all iterations is: 0.7779336734693879
All Done :)
Random seeds are: [677]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
156
Training Models...
getting predictions of each model...
Pca is: 156
Average f1 micro of all iterations is: 0.779824561403509
All Done :)
Random seeds are: [983]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
157
Training Models...
getting predictions of each model...
Pca is: 157
Average f1 micro of all iterations is: 0.7814039408866997
All Done :)
Random seeds are: [103]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
158
Training Models...
getting predictions of each model...
Pca is: 158
Average f1 micro of all iterations is: 0.78317191283293
All Done :)
Random seeds are: [493]
---

Normalizing and applying PCA...
183
Training Models...
getting predictions of each model...
Pca is: 183
Average f1 micro of all iterations is: 0.8120748299319734
All Done :)
Random seeds are: [918]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
184
Training Models...
getting predictions of each model...
Pca is: 184
Average f1 micro of all iterations is: 0.8126890756302527
All Done :)
Random seeds are: [941]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
185
Training Models...
getting predictions of each model...
Pca is: 185
Average f1 micro of all iterations is: 0.8131229235880404
All Done :)
Random seeds are: [516]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
186
Training Models...
getting predictions of each model...
Pca is: 186
Av

Normalizing and applying PCA...
211
Training Models...
getting predictions of each model...
Pca is: 211
Average f1 micro of all iterations is: 0.8208545918367347
All Done :)
Random seeds are: [476]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
212
Training Models...
getting predictions of each model...
Pca is: 212
Average f1 micro of all iterations is: 0.820670037926675
All Done :)
Random seeds are: [168]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
213
Training Models...
getting predictions of each model...
Pca is: 213
Average f1 micro of all iterations is: 0.8208020050125313
All Done :)
Random seeds are: [196]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
214
Training Models...
getting predictions of each model...
Pca is: 214
Ave

Normalizing and applying PCA...
239
Training Models...
getting predictions of each model...
Pca is: 239
Average f1 micro of all iterations is: 0.8221938775510205
All Done :)
Random seeds are: [280]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
240
Training Models...
getting predictions of each model...
Pca is: 240
Average f1 micro of all iterations is: 0.8221884498480243
All Done :)
Random seeds are: [773]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
241
Training Models...
getting predictions of each model...
Pca is: 241
Average f1 micro of all iterations is: 0.8222334004024144
All Done :)
Random seeds are: [743]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
242
Training Models...
getting predictions of each model...
Pca is: 242
Av

Normalizing and applying PCA...
267
Training Models...
getting predictions of each model...
Pca is: 267
Average f1 micro of all iterations is: 0.8287414965986392
All Done :)
Random seeds are: [11]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
268
Training Models...
getting predictions of each model...
Pca is: 268
Average f1 micro of all iterations is: 0.8292054099746403
All Done :)
Random seeds are: [947]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
269
Training Models...
getting predictions of each model...
Pca is: 269
Average f1 micro of all iterations is: 0.8295798319327726
All Done :)
Random seeds are: [317]
--------------------------------- Iteration 0--------------------------------- 

Equalizing Data...
Normalizing and applying PCA...
270
Training Models...
getting predictions of each model...
Pca is: 270
Ave

C:\Users\RS3\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\RS3\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\RS3\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
i=0
counter=0
one_prediction=[]
patient_prediction=[]
patient_test=[]
while i < len(y_test):
    one_prediction.append(voted_prediction[i])
    counter+=1
    if counter == 5:
        #append most common into final one
        patient_prediction.append(most_common(one_prediction))
        patient_test.append(Xandy[0][3][i])
        counter=0
        one_prediction=[]
    i+=1
print(patient_prediction)
print(patient_test)

In [69]:
cm=[[0,0,0],
    [0,0,0],
    [0,0,0]]
for i in range(len(patient_prediction)):
    a=patient_prediction[i]
    b=patient_test[i]
    if a == b and a=='covid':
        cm[0][0]=cm[0][0]+1
    if a == b and a=='pneumonia':
        cm[1][1]=cm[1][1]+1
    if a == b and a=='regular':
        cm[2][2]=cm[2][2]+1
    if a=='covid' and b=='pneumonia':
        cm[0][1]=cm[0][1]+1
    if a=='covid' and b=='regular':
        cm[0][2]=cm[0][2]+1
    if a=='pneumonia' and b=='covid':
        cm[1][0]=cm[1][0]+1
    if a=='pneumonia' and b=='regular':
        cm[1][2]=cm[1][2]+1
    if a=='regular' and b=='covid':
        cm[2][0]=cm[2][0]+1
    if a=='regular' and b=='pneumonia':
        cm[2][1]=cm[2][1]+1

In [70]:
print(cm[0])
print(cm[1])
print(cm[2])

[2, 1, 1]
[0, 4, 2]
[0, 0, 12]
